import {
  numberRandow,
} from '../utils'

/** Screen size breakpoint  */
export const breakpoint = {
  mobile: 425,
  tablet: 768,
  laptop: 1024,
  desktop: 1440,
}

/** Race configs */
export const race = {
  'Anão': {
    strength: numberRandow(1, 3),
    dexterity: numberRandow(0, 2),
    constitution: numberRandow(1, 3),
    intelligence: numberRandow(-1, 1),
    wisdom: numberRandow(0, 2),
    charisma: numberRandow(-1, 1),
  }, 
  'Elfo': {
    strength: numberRandow(-1, 1),
    dexterity: numberRandow(1, 3),
    constitution: numberRandow(-1, 1),
    intelligence: numberRandow(1, 3),
    wisdom: numberRandow(0, 2),
    charisma: numberRandow(0, 2),
  }, 
  'Halfling': {
    strength: numberRandow(-1, 1),
    dexterity: numberRandow(1, 3),
    constitution: numberRandow(-1, 1),
    intelligence: numberRandow(0, 2),
    wisdom: numberRandow(0, 2),
    charisma: numberRandow(1, 3),
  }, 
  'Humano': {
    strength: numberRandow(-1, 1),
    dexterity: numberRandow(1, 3),
    constitution: numberRandow(-1, 1),
    intelligence: numberRandow(1, 3),
    wisdom: numberRandow(0, 2),
    charisma: numberRandow(0, 2),
  }, 
  'Gnomo': {
    strength: numberRandow(-1, 1),
    dexterity: numberRandow(0, 2),
    constitution: numberRandow(0, 2),
    intelligence: numberRandow(1, 3),
    wisdom: numberRandow(-1, 1),
    charisma: numberRandow(1, 3),
  }, 
  'Orc': {
    strength: numberRandow(1, 3),
    dexterity: numberRandow(0, 2),
    constitution: numberRandow(1, 3),
    intelligence: numberRandow(0, 2),
    wisdom: numberRandow(-1, 1),
    charisma: numberRandow(-1, 1),
  }, 
  'Goblinoide': {
    strength: numberRandow(0, 2),
    dexterity: numberRandow(1, 3),
    constitution: numberRandow(1, 3),
    intelligence: numberRandow(-1, 1),
    wisdom: numberRandow(-1, 1),
    charisma: numberRandow(0, 2),
  }, 
  'Tiefling': {
    strength: numberRandow(-1, 1),
    dexterity: numberRandow(0, 2),
    constitution: numberRandow(-1, 1),
    intelligence: numberRandow(1, 3),
    wisdom: numberRandow(0, 2),
    charisma: numberRandow(1, 3),
  }, 
  'Nefilin': {
    strength: numberRandow(0, 2),
    dexterity: numberRandow(-1, 1),
    constitution: numberRandow(0, 2),
    intelligence: numberRandow(1, 3),
    wisdom: numberRandow(1, 3),
    charisma: numberRandow(-1, 1),
  }, 
  'Licantropo': {
    strength: numberRandow(1, 3),
    dexterity: numberRandow(0, 2),
    constitution: numberRandow(1, 3),
    intelligence: numberRandow(-1, 1),
    wisdom: numberRandow(0, 2),
    charisma: numberRandow(-1, 1),
  }, 
  'Gigante': {
    strength: numberRandow(1, 3),
    dexterity: numberRandow(-1, 1),
    constitution: numberRandow(1, 3),
    intelligence: numberRandow(0, 2),
    wisdom: numberRandow(0, 2),
    charisma: numberRandow(-1, 1),
  }, 
  'Fada': {
    strength: numberRandow(-1, 1),
    dexterity: numberRandow(1, 3),
    constitution: numberRandow(-1, 1),
    intelligence: numberRandow(0, 2),
    wisdom: numberRandow(1, 3),
    charisma: numberRandow(0, 2),
  },
}

/** Caste configs */
export const caste = {
  'Bárbaro': {
    life: numberRandow(12, 16),
    coins: numberRandow(10, 18),
    actions: numberRandow(3, 7),
  },
  'Bardo': {
    life: numberRandow(8, 12),
    coins: numberRandow(10, 20),
    actions: numberRandow(3, 5),
  },
  'Bruxo': {
    life: numberRandow(8, 12),
    coins: numberRandow(10, 16),
    actions: numberRandow(3, 5),
  },
  'Clérigo': {
    life: numberRandow(8, 12),
    coins: numberRandow(10, 20),
    actions: numberRandow(3, 5),
  },
  'Druida': {
    life: numberRandow(8, 12),
    coins: numberRandow(10, 18),
    actions: numberRandow(3, 5),
  },
  'Feiticeiro': {
    life: numberRandow(6, 10),
    coins: numberRandow(8, 12),
    actions: numberRandow(3, 4),
  },
  'Guerreiro': {
    life: numberRandow(10, 14),
    coins: numberRandow(10, 20),
    actions: numberRandow(3, 6),
  },
  'Ladino': {
    life: numberRandow(8, 12),
    coins: numberRandow(10, 16),
    actions: numberRandow(3, 5),
  },
  'Mago': {
    life: numberRandow(6, 10),
    coins: numberRandow(10, 16),
    actions: numberRandow(3, 4),
  },
  'Monge': {
    life: numberRandow(8, 12),
    coins: numberRandow(6, 10),
    actions: numberRandow(3, 5),
  },
  'Paladino': {
    life: numberRandow(10, 14),
    coins: numberRandow(10, 20),
    actions: numberRandow(3, 6),
  },
  'Patrulheiro': {
    life: numberRandow(10, 14),
    coins: numberRandow(8, 12),
    actions: numberRandow(3, 6),
  }
}

/** Tendecy options */
export const tendency = [
  'Bom', 
  'Leal', 
  'Neutro', 
  'Caótico',
  'Mau',
]

/** Adventures options */
export const adventures = [
  'Escoltar um personagem',
  'Matar um personagem',
  'Proteger um personagem',
  'Prender um personagem',
  'Investigar um personagem',
  'Matar um monstro',
  'Defender um monstro',
  'Libertar um monstro',
  'Capturar um monstro',
  'Encontrar um monstro',
  'Escapar de um monstro',
  'Caçar um animal',
  'Defender um animal',
  'Libertar um animal',
  'Capturar um animal',
  'Procurar um animal',
  'Entregar um animal',
  'Libertar um personagem',
  'Encontrar um objeto',
  'Proteger um objeto',
  'Entregar um objeto',
  'Destruir um objeto',
  'Recuperar um objeto',
  'Roubar um objeto',
  'Encontrar um local',
  'Chegar em um local',
  'Proteger um local',
  'Mapear um local',
  'Escapar de um local',
  'Destruir um local',
]

/** Scenarios options */
export const scenarios = [
  'Floresta',
  'Pântano',
  'Montanha',
  'Mar',
  'Ártico',
  'Deserto',
  'Colina',
  'Planíce',
  'Metrópole',
  'Reino',
  'Cidade',
  'Vila',
  'Aldeia',
  'Povoado',
]

/** Characters options */
export const characters = [
  'Bárbaro',
  'Bardo',
  'Bruxo',
  'Clérigo',
  'Druida',
  'Feiticeiro',
  'Guerreiro',
  'Ladino',
  'Mago',
  'Monge',
  'Paladino',
  'Patrulheiro',
  'Acólito',
  'Artesão',
  'Mercador',
  'Artista',
  'Gladiador',
  'Charlatão',
  'Criminoso',
  'Espião',
  'Eremita',
  'Forasteiro',
  'Andarilho',
  'Herói do Povo',
  'Marinheiro',
  'Pirata',
  'Nobre',
  'Cavaleiro',
  'Orfão',
  'Sábio',
  'Pesquisador',
  'Soldado',
]

/** Objects options */
export const objects = [
  'Arma', 
  'Armadura', 
  'Equipamento', 
  'Ferramenta', 
  'Recipiente', 
  'Utensílio', 
  'Mobília', 
  'Vestimenta', 
  'Precioso', 
  'Mágico', 
  'Estudo', 
  'Alimento', 
  'Bebida', 
  'Veículo', 
  'Instrumento',
]

/** Places options */
export const places = [
  'Casa', 
  'Cemitério', 
  'Bibliteca', 
  'Hospedaria', 
  'Igreja', 
  'Museu', 
  'Teatro', 
  'Escola', 
  'Hospital', 
  'Taverna', 
  'Restaurante', 
  'Armazém', 
  'Loja', 
  'Ponte', 
  'Praça', 
  'Torre', 
  'Rio', 
  'Lago', 
  'Caverna', 
  'Gruta', 
  'Cachoeira', 
  'Penhasco', 
  'Ruína', 
  'Templo',
  'Barco',
  'Santuário', 
  'Covil',
]