name: Rollback

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag de rollback (v#.#.#)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Rollback via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/rpg-prod/RPGdeMesa-web-
            git fetch --tags origin
            git checkout ${{ inputs.tag }}
            npm ci
            npm run build
